export const projectDetailsList = [

    {
        name: "Hatly",
        slug: "hatly",
        info: "E-commerce Multi Vendor, Super Mart & Rider App",
        liveURL: "https://hatly.ae/",
        liveURLText: "hatly.ae",
        description: "Hatly is a comprehensive e-commerce platform designed to rival the popular Talabat app in the UAE, offering a seamless, multi-vendor marketplace experience tailored for restaurants, product stores, and diverse merchants. This versatile application includes features for a wide range of needs: users can browse and order from multiple restaurants and product stores, ensuring access to a variety of food, groceries, and retail items in one convenient place. Hatly also integrates its own Super Mart, providing quick access to daily essentials with optimized delivery times. Additionally, Hatly's Rider App enhances customer experience with reliable pick-and-drop services, allowing users to schedule or request personal item deliveries with ease. To support effective management and growth, Hatly includes a powerful admin panel that provides in-depth insights and analytics on customers, vendors, and riders, equipping administrators with data to monitor performance, optimize operations, and drive user engagement. Whether for dining, shopping, or on-demand logistics, Hatly combines these capabilities into a single, user-friendly application built to meet the modern consumer's needs.",
        bannerImage: "https://res.cloudinary.com/dh7kygocu/image/upload/v1726927958/hatly%20images/g3brp3htl2fpufstbva2.jpg",
        images: [
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918258/hatly%20images/hbug8vbzaa0olsmczctd.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918258/hatly%20images/lzyjjfzhnu6005jiscuy.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918259/hatly%20images/zjs3v9bdbviqlxqre0js.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918261/hatly%20images/wnyuj08yfc8ut4doddl1.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918259/hatly%20images/mkkva6b82bf3h9egkflq.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918260/hatly%20images/dood6em6xpi5xpq21s8g.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918260/hatly%20images/jnpzciozrq4as5mmkqgo.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918261/hatly%20images/yhmjr3zglnwspz6fclct.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918258/hatly%20images/vzyfrbpzkbqofjzohesl.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918259/hatly%20images/urzfdm4zmjflqzw3kk2z.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918261/hatly%20images/ztjsriunqnkbeamfp2iq.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918262/hatly%20images/ccgfyefadflytnqxy7l4.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918259/hatly%20images/xpkjljoz6bbbsi0ruahw.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918262/hatly%20images/fesm23gqbvfemyaombmb.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918262/hatly%20images/jli1kk7to2h2d9yzfnwi.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918261/hatly%20images/h03ipakye2ejoihnobz7.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918261/hatly%20images/msbbt5f1qbdahtujxogs.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918261/hatly%20images/begexytoo6zzu8aftu5r.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918260/hatly%20images/rdnkyt7nlcejaepdyyip.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918260/hatly%20images/zfw9uitxkvlgixetw3d0.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918260/hatly%20images/kkqtkxpqbclfmx7hhmh9.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918259/hatly%20images/dkzvpvewshf3g3enqlvb.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918259/hatly%20images/xflksqkabv5qkdbffqm1.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721918259/hatly%20images/wmvnlmveihklxqu0cguu.png",
        ]
    },
    {
        name: "E-Quiz",
        slug: "e-quiz",
        info: "Quizes, Raffles, E-commerce, Lucky draws and prises app.",
        liveURL: "https://staging.emiratesq.net/",
        liveURLText: "emiratesq.net",
        description: 'E Quiz is an engaging web application that blends knowledge, rewards, and entertainment. Users can participate in regional quizzes to earn points, which can be redeemed for products from the integrated e-commerce panel. The platform also offers exciting raffles and lucky draws, giving users opportunities to win exclusive prizes. With its unique "Active User Ranking" system, users can earn points by spending time on the app, while a digital wallet allows them to manage and top up their points effortlessly. Subscription plans further enhance the experience by doubling top-up points and increasing winning chances in raffles and draws. E-Quiz transforms knowledge and activity into valuable rewards, making it a fun and rewarding experience for all.',
        bannerImage: "https://res.cloudinary.com/dh7kygocu/image/upload/v1724280540/equiz-web-app/w53telkuews1ibjyilms.png",
        images: [
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389164/equiz-web-app/eqtpfmp2auwwqxuueaki.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389164/equiz-web-app/ewnr1xkaiwdaon3sy8wo.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389166/equiz-web-app/spdbvarvekgt0uqmlkee.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389165/equiz-web-app/glpwxpalngml84ueac8a.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389166/equiz-web-app/ctdvmqpiwob1hyjcjjva.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389165/equiz-web-app/dvg9hgadvy7ebmhmzvni.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389167/equiz-web-app/kssotiof12snrs5yxzh2.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389164/equiz-web-app/kkmivvnljnoe9ohtly3w.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389167/equiz-web-app/bi61cdkt7ja2pdmdhd5n.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389167/equiz-web-app/n6omly2qxmp3qnwevi6r.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389168/equiz-web-app/jwvrhwfeavzceev9vozg.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389168/equiz-web-app/icqbhpmzembocw22skdp.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389168/equiz-web-app/btejqb4smj5z0ogijwij.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389168/equiz-web-app/cym1ws4fq8ap9qrulsvo.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389167/equiz-web-app/doab8mqnoejayhqpzhqo.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389167/equiz-web-app/qkrbqgbkja9bb6zhu1js.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389167/equiz-web-app/emfb48b0vte7wryfxizu.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389167/equiz-web-app/dczk274rdcvc0dhufzpn.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389167/equiz-web-app/mrcvqm088lvz0736shk1.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389166/equiz-web-app/o7jop0azqwsys30xaevd.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389166/equiz-web-app/bxh3v6mvqnw03mpxtnff.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389166/equiz-web-app/ohulrwx6karyzaglvajf.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389166/equiz-web-app/wztvtahomzfwgsolz6rw.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389166/equiz-web-app/on2jcwmrnw9uo75jbnze.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389165/equiz-web-app/e8tze9cdmymsut6pzdrd.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389165/equiz-web-app/ogaa1lqf79uoegvhhorf.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389165/equiz-web-app/fabyxpr9rkbxlreuvexx.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389164/equiz-web-app/xchlfxfc2r0f5ry7hzff.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389164/equiz-web-app/hv19dqqaemce0cdigzcs.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1721389164/equiz-web-app/lmp45hsvbuvtkt7to8ew.png",
        ]
    },
    {
        name: "Raseef",
        slug: "raseef",
        info: "E-commerce Multi Vendor and Admin App.",
        liveURL: "https://raseef.app/",
        liveURLText: "raseef.app",
        description: 'Raseef is an E-commerce Multivendor web application designed to empower vendors and streamline their business operations. Vendors can register, purchase subscription plans, and set up their online shops to sell products seamlessly. The platform enables vendors to track customers in real time with advanced customer tracking features, including integration with Google Maps for multiple tracking types. A built-in chat system allows vendors to communicate directly with customers, enhancing engagement and support.To manage their operations efficiently, vendors can use the staff panel to create staff accounts, assign specific roles, and delegate responsibilities as needed. Additionally, VendorHub includes a robust admin panel where administrators can oversee all users and vendors, monitor activities, and manage the system effectively. Admins have the authority to ban or unban users and vendors, as well as track subscription metrics, ensuring the platform runs smoothly. VendorHub offers a powerful solution for vendors and administrators alike, fostering a productive and secure online marketplace.',
        bannerImage: "https://res.cloudinary.com/dh7kygocu/image/upload/v1724279850/raseef%20images/y1uvohjaqraedmfivimy.png",
        images: [
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1724279111/raseef%20images/sg1mx6pgbbqotymj5we8.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710820/raseef%20images/fxnounguu1jr6b2f6h8l.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710821/raseef%20images/cp77i8heg4tducsmuk5v.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710823/raseef%20images/hjtk8stkxhblwxfhplv8.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710822/raseef%20images/q1tlx1aqnbkedlex4zuc.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710823/raseef%20images/abisplnevcbz0p6iz3qb.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710821/raseef%20images/mlk9bsjqjqzbiq462bpk.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710822/raseef%20images/tgciilyg68x8w6cmrzi0.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710820/raseef%20images/fuknl3pqfdh4qbr7s9c0.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710820/raseef%20images/tqqygbxc2wb324ehnotz.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710823/raseef%20images/rqugamotjlaetgf4l0zl.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710822/raseef%20images/u79eodgisgylavjw3jok.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710822/raseef%20images/xmqax2dc4rasfqnaqp4r.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710822/raseef%20images/likg1vrp7fusfj0saelt.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710821/raseef%20images/xosd7rdq5hjtf5utkj5b.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710821/raseef%20images/wurdhyknrduo3qoqe84k.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710821/raseef%20images/pe5b9lopvjwrrh05qt1c.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710820/raseef%20images/qhcrdhmqi0pzpgylhqao.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710820/raseef%20images/la2fj282clpkc6zic4ij.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710820/raseef%20images/vpurwrttpim5tfcw1pee.png",
            "https://res.cloudinary.com/dh7kygocu/image/upload/v1720710820/raseef%20images/iho92usont1bddydh38o.png",
        ]
    },
    {
        name: "Zues Multi Vendor",
        slug: "zues-multi-vendor",
        info: "E-commerce Multi Vendor, Broker panel and Admin panel web app.",
        liveURL: "https://raseef.app/",
        liveURLText: "raseef.app",
        description: '',
        bannerImage: "https://res.cloudinary.com/dh7kygocu/image/upload/v1726928467/zues-admin-panel/gk5bzcsljmh9jer2xshi.jpg",
        images: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
        ]
    }
]